---
- name: Playbook for checking HANA Services
  hosts: all,localhost
  gather_facts: false
  tasks:
    - name: Save the result of 'whoami' in 'whoami_out'
      win_command: wmic qfe list
      register: whoami_out