---
- name: Display MOTD playbook
  hosts: all
  gather_facts: true
  tasks: 
    - name: Configure a MOTD (message of the day)
      copy:
        content: Welcome to CentOS Linux - Ansible Rocks
        dest: /etc/motd