---
-
    #Target: where our play books will run and with what options
    #hosts: centoshosts
    #user: root

    #Tasks: the list of tasks that will be executed with the playbook
    tasks: 
        -name: Configure a MOTD (message of the day)
        copy:
            src: centos_motd
            dest: /etc/motd
...