---
- name: Display MOTD playbook
  hosts: all
  gather_facts: true
  vars:
    motd: "Welcome to CentOS Linix - Ansible Rocks\n"
  tasks: 
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd